<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->truncate();
        DB::table('products')->insert([
            [
                'title' => '芹菜 半斤',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-vg@1.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '梨花带雨 3个',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-dryfruit@1.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '素米 327克',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-rice@1.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '红袖枸杞 6克*3袋',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-tea@1.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '春生龙眼 500克',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-dryfruit@2.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '小红的猪耳朵 120克',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-cake@2.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '泥蒿 半斤',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-vg@2.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '夏日芒果 3个',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-dryfruit@3.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '冬木红枣 500克',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-dryfruit@4.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '万紫千凤梨 300克',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-dryfruit@5.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '贵妃笑 100克',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-dryfruit-a@6.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '珍奇异果 3个',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-dryfruit@7.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '绿豆 125克',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-rice@2.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '芝麻 50克',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-rice@3.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '猴头菇 370克',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-rice@4.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '西红柿 1斤',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-vg@3.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '油炸花生 300克',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-fry@1.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '春泥西瓜子 128克',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-fry@2.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '碧水葵花籽 128克',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-fry@3.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '碧螺春 12克*3袋',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-tea@2.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '西湖龙井 8克*3袋',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-tea@3.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '梅兰清花糕 1个',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-cake-a@3.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '清凉薄荷糕 1个',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-cake-a@4.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '小明的妙脆角 120克',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-cake@1.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '红衣青瓜 混搭160克',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-dryfruit@8.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '锈色瓜子 100克',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-fry@4.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '春泥花生 200克',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-fry@5.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '冰心鸡蛋 2个',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-rice@5.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '八宝莲子 200克',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-rice@6.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '深涧木耳 78克',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-rice@7.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '土豆 半斤',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-vg@4.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
            [
                'title' => '青椒 半斤',
                'price' => '0.01',
                'stock' => '999',
                'main_img' => 'storage/attachment/20200521/product-vg@5.png',
                'image_list' => '',
                'pc_desc' => '',
                'wap_desc' => '',
            ],
        ]);
    }
}
